### ISSUE TITLE
gulp-symdest does not preserve links on electron

### ISSUE THREAD

**Issue by bpasero** [joaomoreno/gulp-symdest#1]
Noticed this today from the VSCode build, the links in Electron are no longer preserved when using symdest. I wonder if some dependency has changed that could cause this?

When we debugged it, https://github.com/joaomoreno/gulp-symdest/blob/master/index.js#L30 was never hit although we had symlinks.

**Comment by joaomoreno** [comment]
Code looks good. Something is wrong in the VSCode build.
